#!/usr/bin/env bash
# scripts/setup-ubuntu.sh — Install PostgreSQL 16 + Redis 7 on Ubuntu 24.04
#
# Run as root or with sudo:
#   sudo bash scripts/setup-ubuntu.sh
#
# What it does:
#   1. Installs postgresql-16 and redis-server
#   2. Creates the 'arena' database role and database
#   3. Generates strong random passwords
#   4. Writes /etc/arena/.env with connection credentials
#   5. Applies the initial schema (migrations/001_initial_schema.sql)
#   6. Configures Redis with a password and AOF persistence
#   7. Enables both services on startup
#
# After running, copy /etc/arena/.env into your project .env

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────

DB_NAME="arena"
DB_USER="arena"
DB_PASS=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
REDIS_PASS=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
ENV_DIR="/etc/arena"
ENV_FILE="$ENV_DIR/.env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

info()    { echo -e "\033[1;34m[setup]\033[0m $*"; }
success() { echo -e "\033[1;32m[ok]\033[0m $*"; }
warn()    { echo -e "\033[1;33m[warn]\033[0m $*"; }
die()     { echo -e "\033[1;31m[error]\033[0m $*"; exit 1; }

# ── PostgreSQL ────────────────────────────────────────────────────────────────

info "Updating apt and installing PostgreSQL 16…"
apt-get update -q
apt-get install -y -q postgresql-16 postgresql-client-16

info "Starting PostgreSQL…"
systemctl enable postgresql
systemctl start postgresql

info "Creating database role and database…"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASS';
  ELSE
    ALTER ROLE $DB_USER WITH PASSWORD '$DB_PASS';
  END IF;
END \$\$;

SELECT 'CREATE DATABASE $DB_NAME OWNER $DB_USER'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME')
\gexec

GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
SQL

success "PostgreSQL: database '$DB_NAME' ready, user '$DB_USER' created"

# ── Redis ─────────────────────────────────────────────────────────────────────

info "Installing Redis 7…"
apt-get install -y -q redis-server

info "Configuring Redis (password + AOF persistence)…"
REDIS_CONF="/etc/redis/redis.conf"

# Set password
if grep -q "^requirepass" "$REDIS_CONF"; then
  sed -i "s/^requirepass .*/requirepass $REDIS_PASS/" "$REDIS_CONF"
else
  echo "requirepass $REDIS_PASS" >> "$REDIS_CONF"
fi

# Enable AOF persistence (survive restarts)
sed -i 's/^appendonly no/appendonly yes/' "$REDIS_CONF"

# Bind to localhost only (security)
sed -i 's/^bind .*/bind 127.0.0.1 -::1/' "$REDIS_CONF"

info "Starting Redis…"
systemctl enable redis-server
systemctl restart redis-server

success "Redis configured and running"

# ── Write credentials ─────────────────────────────────────────────────────────

info "Writing credentials to $ENV_FILE…"
mkdir -p "$ENV_DIR"
chmod 750 "$ENV_DIR"

cat > "$ENV_FILE" <<ENV
# Agent Arena — Database Credentials
# Generated by setup-ubuntu.sh on $(date -Iseconds)
# Copy this to your project .env file.

# PostgreSQL
PGHOST=localhost
PGPORT=5432
PGDATABASE=$DB_NAME
PGUSER=$DB_USER
PGPASSWORD=$DB_PASS
PG_POOL_MAX=20
PG_STATEMENT_TIMEOUT=10000

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=$REDIS_PASS
REDIS_PREFIX=arena:

# JWT (change this!)
JWT_SECRET=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64)

# Service ports
PORT_IDENTITY=3001
PORT_GATEWAY=3002
ENV

chmod 640 "$ENV_FILE"
success "Credentials written to $ENV_FILE"

# ── Apply schema ──────────────────────────────────────────────────────────────

SCHEMA_FILE="$PROJECT_ROOT/migrations/001_initial_schema.sql"

if [[ -f "$SCHEMA_FILE" ]]; then
  info "Applying database schema…"
  PGPASSWORD="$DB_PASS" psql -h localhost -U "$DB_USER" -d "$DB_NAME" -f "$SCHEMA_FILE" \
    && success "Schema applied" \
    || warn "Schema apply failed — run manually: node scripts/migrate.js"
else
  warn "Schema file not found at $SCHEMA_FILE — run 'node scripts/migrate.js' manually"
fi

# ── Final check ───────────────────────────────────────────────────────────────

info "Running connectivity checks…"

if PGPASSWORD="$DB_PASS" psql -h localhost -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1" -q > /dev/null 2>&1; then
  success "PostgreSQL connection: OK"
else
  warn "PostgreSQL connection check failed — check logs: journalctl -u postgresql"
fi

if redis-cli -a "$REDIS_PASS" --no-auth-warning PING 2>/dev/null | grep -q PONG; then
  success "Redis connection: OK"
else
  warn "Redis connection check failed — check logs: journalctl -u redis-server"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo " Credentials saved to: $ENV_FILE"
echo ""
echo " Next steps:"
echo "   1. cp $ENV_FILE /your/project/.env"
echo "   2. node scripts/migrate.js"
echo "   3. node scripts/seed.js          (optional test data)"
echo "   4. cd arena-identity && npm start"
echo "   5. cd arena-gateway  && npm start"
echo ""
